### ISSUE TITLE
incorrect url for ingestion notebook

### ISSUE THREAD

**Issue by cfarre** [Azure/BatchSparkScoringPredictiveMaintenance#34]
this URL returns 404
basedataurl = "http://media.githubusercontent.com/media/Microsoft/SQL-Server-R-Services-Samples/master/PredictiveMaintanenceModelingGuide/Data/

we tried to point to basedataurl = "https://media.githubusercontent.com/media/Microsoft/SQL-Server-R-Services-Samples/master/PredictiveMaintenanceModelingGuide/Data/"

 and is returning this error

CParserError                              Traceback (most recent call last)
<command-1773370605680580> in <module>()
      7 
      8 # Read into pandas
----> 9 machines = pd.read_csv(datafile, encoding='utf-8')
     10 
     11 # The data was read in using a Pandas data frame. We'll convert

**Comment by ehrlinger** [comment]
Can you try the latest version of the notebook to see if this solves the issue you're seeing? I may have already corrected this. I just PRd this one.

**Comment by cfarre** [comment]
still no luck
HTTPError                                 Traceback (most recent call last)
<command-4159498550139609> in <module>()
      4 # Download the file once, and only once.
      5 if not os.path.isfile(datafile):
----> 6     urllib.request.urlretrieve(basedataurl+datafile, datafile)
      7 
      8 # Read into pandas

/usr/lib/python3.5/urllib/request.py in urlretrieve(url, filename, reporthook, data)
    186     url_type, path = splittype(url)
    187 
--> 188     with contextlib.closing(urlopen(url, data)) as fp:
    189         headers = fp.info()
    190 

/usr/lib/python3.5/urllib/request.py in urlopen(url, data, timeout, cafile, capath, cadefault, context)

**Comment by cfarre** [comment]
ok I passed that and now we are getting other errors. I suggest doing a end to end qa on the whole solution since this is not stable enough for us

Py4JJavaError: An error occurred while calling o214._run.
: com.databricks.WorkflowException: com.databricks.NotebookExecutionException: FAILED
	at com.databricks.workflow.WorkflowDriver.run(WorkflowDriver.scala:74)
	at com.databricks.dbutils_v1.impl.NotebookUtilsImpl.run(NotebookUtilsImpl.scala:90)
	at com.databricks.dbutils_v1.impl.NotebookUtilsImpl._run(NotebookUtilsImpl.scala:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:380)
	at py4j.Gateway.invoke(Gateway.java:295)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:251)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.databricks.NotebookExecutionException: FAILED
	at com.databricks.workflow.WorkflowDriver.run0(WorkflowDriver.scala:116)
	at com.databricks.workflow.WorkflowDriver.run(WorkflowDriver.scala:61)
	... 13 more

**Comment by ehrlinger** [comment]
This is a different issue, not sure how to debug this one. I'll close the original issue as it was cause by a change in an external dependency.
